version: '3.8'
services:
  easystore-db:
    image: mysql:8.0
    container_name: easystore_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easystore_db
    ports:
      - "3306:3306" #host in machine:host in container
    volumes:
      - easystore_data:/var/lib/mysql
volumes:
  easystore_data: